---
alternate: true
executions: 10
scenarios:
- name: scenario A
  workingDir: "/tmp"
  env:
    KEY: value
  setup:
    cmd:
    - echo
    - setupA
  teardown:
    cmd:
    - echo
    - teardownA

  beforeCommand:
    workingDir: "/another-path"
    cmd:
    - echo
    - beforeA
  afterCommand:
    cmd:
    - echo
    - afterA
  command:
    cmd:
    - sleep
    - '1'
- name: scenario B
  command:
    cmd:
    - sleep
    - '0'