---
alternate: true
executions: 2
scenarios:
- name: scenario A
  workingDir: "/tmp"
  env:
    KEY: value
  before:
    cmd:
    - echo
    - beforeA
  after:
    cmd:
    - echo
    - afterA
  script:
  - cmd:
    - sleep
    - '1'
- name: scenario B
  script:
  - cmd:
    - sleep
    - '0'
  - cmd:
    - sleep
    - '1'
